Repository newrelic/newrelic-winston-logenricher-node, pull requests merged in 2020-10, with the labels that each got.

#37 Adds Node 14 to CI.
  .github/workflows/ci-workflow.yaml
Labels: risk: low, semver: minor

#39 Remove Node v8.x from CI
  CODE_OF_CONDUCT.md
  package.json
  tests/versioned/package.json
Labels: risk: low, semver: major

#43 Still log when disabled
  lib/createFormatter.js
  tests/versioned/winston.tap.js
Labels: risk: low, semver: patch

#44 Move agent dependency to be a peer dependency
  THIRD_PARTY_NOTICES.md
  package.json
  third_party_manifest.json
Labels: risk: low, semver: major
